-- A + M COZY WEBSITE
-- Dieses SQL im Supabase SQL Editor ausführen.
-- VORHER admin@example.com durch DEINE echte Login-E-Mail ersetzen.

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  title text not null,
  date_text text,
  text text not null,
  image_url text not null,
  storage_path text,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.memories enable row level security;

-- Öffentliche Seite darf veröffentlichte Erinnerungen lesen.
drop policy if exists "public can read published memories" on public.memories;
create policy "public can read published memories"
on public.memories
for select
to anon, authenticated
using (published = true);

-- Nur dein Admin-Konto darf alles verwalten.
drop policy if exists "admin can insert memories" on public.memories;
create policy "admin can insert memories"
on public.memories
for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'admin@example.com');

drop policy if exists "admin can delete memories" on public.memories;
create policy "admin can delete memories"
on public.memories
for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@example.com');

drop policy if exists "admin can update memories" on public.memories;
create policy "admin can update memories"
on public.memories
for update
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@example.com')
with check ((auth.jwt() ->> 'email') = 'admin@example.com');

-- ==========================================================
-- STORAGE
-- Im Supabase Dashboard einen Bucket namens "memories"
-- erstellen und auf "Public" stellen.
-- Danach diese Policies ausführen:
-- ==========================================================

drop policy if exists "admin can upload memory images" on storage.objects;
create policy "admin can upload memory images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'memories'
  and (auth.jwt() ->> 'email') = 'admin@example.com'
);

drop policy if exists "admin can delete memory images" on storage.objects;
create policy "admin can delete memory images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'memories'
  and (auth.jwt() ->> 'email') = 'admin@example.com'
);

drop policy if exists "public can read memory images" on storage.objects;
create policy "public can read memory images"
on storage.objects
for select
to public
using (bucket_id = 'memories');
